USE curso_sql;

CREATE TABLE CONTA_BANCARIA
(
CODIGO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
-- Código interno (PK)
TITULAR VARCHAR(32) NOT NULL, -- Nome do titular da conta
SALDO DOUBLE NOT NULL, -- Representa o saldo da conta
PRIMARY KEY(CODIGO)
-- Define o campo CODIGO como PK (Primary Key)
);
INSERT INTO CONTA_BANCARIA VALUES (1, 'André', 213);
INSERT INTO CONTA_BANCARIA VALUES (2, 'Diogo', 489);
INSERT INTO CONTA_BANCARIA VALUES (3, 'Rafaela', 568);
INSERT INTO CONTA_BANCARIA VALUES (4, 'Carlos', 712);
INSERT INTO CONTA_BANCARIA VALUES (5, 'Pietra', -38);
INSERT INTO CONTA_BANCARIA VALUES (6, 'Luciano', 380);
INSERT INTO CONTA_BANCARIA VALUES (7, 'Ana', 520);
INSERT INTO CONTA_BANCARIA VALUES (8, 'Thays', 120);
INSERT INTO CONTA_BANCARIA VALUES (9, 'Sarah', 80);

SELECT * FROM CONTA_BANCARIA;

start transaction;
UPDATE CONTA_BANCARIA SET SALDO = SALDO * 1.03 WHERE SALDO > 0;
SET SQL_SAFE_UPDATES = 0;
commit;

SELECT * FROM CONTA_BANCARIA;